services:
  - type: web
    name: anime-bot
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: python bot.py
    envVars:
      - key: BOT_TOKEN
        sync: false
      - key: ADMIN_IDS
        sync: false
      - key: DATABASE_URL
        sync: false
      - key: WEBHOOK_URL
        sync: false
      - key: CHANNEL_USERNAME
        value: "@Aniyoof"
      - key: PAYMENT_CARD
        sync: false
      - key: PAYMENT_NAME
        sync: false
      - key: ADMIN_USERNAMES
        sync: false
      - key: ADS_USERNAME
        value: "@Sarvarbek_offf"
      - key: PORT
        value: "8080"